apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-bruker-api
  namespace: toi
spec:
  image: {{image}} # Placeholder variable to be replaced by the CI/CD pipeline
  port: 8080
  replicas:
    max: 4
    min: 2
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
  liveness:
    path: /internal/isAlive
    initialDelay: 40
  readiness:
    path: /internal/isReady
    initialDelay: 40
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true
