/*
 * This source file was generated by the Gradle 'init' task
 */
package no.nav.toi.rekrutteringsbistand.bruker.api

import kotlin.test.Test
import kotlin.test.assertNotNull


class AppTest {
    }
